name: Hedera Solo Integration Tests

on:
  push:
    branches:
      - '**'  
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Setup Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Install setuptools wheel
        run: pip install --upgrade pip setuptools wheel 
      
      - name: Install package with pip e 
        pip install -e .
          
      - name: Prepare Hedera Solo
        id: solo
        uses: OpenElements/hedera-solo-action@v0.4

      - name: Set environment variables
        run: |
          echo "OPERATOR_ID=${{ steps.solo.outputs.accountId }}"
          echo "OPERATOR_KEY=${{ steps.solo.outputs.privateKey }}"
          echo "ADMIN_KEY=${{ steps.solo.outputs.privateKey }}"
          echo "PUBLIC_KEY=${{ steps.solo.outputs.publicKey }}"

      - name: Install your package
        run: pip install -e .

      - name: Run tests
        env:
          OPERATOR_ID: ${{ steps.solo.outputs.accountId }}
          OPERATOR_KEY: ${{ steps.solo.outputs.privateKey }}
          ADMIN_KEY: ${{ steps.solo.outputs.privateKey }}
          PUBLIC_KEY: ${{ steps.solo.outputs.publicKey }}
          NETWORK: solo
        run: |
          python test.py